// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzrsZruat4gVuemCMDGHJb3bFJ04v07Bo',
    appId: '1:590005969071:android:5d8c2a6a1cbd39e7f2745a',
    messagingSenderId: '590005969071',
    projectId: 'fir-sample-9d7e1',
    storageBucket: 'fir-sample-9d7e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5ogKSYa9-ScO9vZGn4711CV1e3mjBQmc',
    appId: '1:590005969071:ios:6ba04fe3480ad8aef2745a',
    messagingSenderId: '590005969071',
    projectId: 'fir-sample-9d7e1',
    storageBucket: 'fir-sample-9d7e1.appspot.com',
    iosClientId: '590005969071-1ed5glk39mi2tppbhgbinpcqqplgeklv.apps.googleusercontent.com',
    iosBundleId: 'com.andronerds.firebaseSample',
  );
}
